/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-container-highest': '#efdfda',
        'tertiary-container': '#005063',
        'tertiary-fixed-dim': '#94cfe6',
        secondary: '#944a00',
        'on-error': '#ffffff',
        surface: '#fff8f6',
        background: '#fff8f6',
        'secondary-container': '#fc8f34',
        'inverse-on-surface': '#feede8',
        'primary-fixed-dim': '#ffb59b',
        'secondary-fixed': '#ffdcc5',
        'surface-dim': '#e7d7d2',
        'on-secondary-fixed-variant': '#713700',
        'primary-fixed': '#ffdbcf',
        'on-primary': '#ffffff',
        'surface-container-high': '#f5e5e0',
        'secondary-fixed-dim': '#ffb783',
        'on-tertiary-container': '#85c1d7',
        'on-primary-container': '#ffa17f',
        'inverse-surface': '#382e2b',
        'outline-variant': '#dac1b9',
        outline: '#87736c',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#b6ebff',
        'on-tertiary-fixed': '#001f28',
        'primary-container': '#7a3419',
        'on-secondary-fixed': '#301400',
        'on-surface-variant': '#54433d',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#004e60',
        'on-primary-fixed': '#380d00',
        tertiary: '#003846',
        'surface-container': '#fbeae6',
        'surface-container-low': '#fff1ec',
        'surface-bright': '#fff8f6',
        'inverse-primary': '#ffb59b',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#221a17',
        'on-secondary': '#ffffff',
        'surface-variant': '#efdfda',
        'surface-tint': '#95482c',
        'on-secondary-container': '#663100',
        primary: '#5c1e05',
        'on-background': '#221a17',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        unit: '8px',
        gutter: '24px',
      },
      fontFamily: {
        'body-lg': ['Satoshi', 'sans-serif'],
        'label-caps': ['Satoshi', 'sans-serif'],
        'body-md': ['Satoshi', 'sans-serif'],
        'headline-lg': ['"Instrument Serif"', 'serif'],
        'headline-md': ['"Instrument Serif"', 'serif'],
        'display-lg-mobile': ['"Instrument Serif"', 'serif'],
        'display-lg': ['"Instrument Serif"', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.0', letterSpacing: '0.15em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '1.05', fontWeight: '400' }],
        'display-lg': ['96px', { lineHeight: '0.95', letterSpacing: '-0.03em', fontWeight: '400' }],
      },
      backgroundImage: {
        'paper-texture':
          'repeating-linear-gradient(45deg, transparent, transparent 10px, rgba(135, 115, 108, 0.05) 10px, rgba(135, 115, 108, 0.05) 11px)',
      },
    },
  },
}
